name: StickyCommands
version: 3.1.5-afkfix
main: com.dumbdogdiner.stickycommands.StickyCommands
load: STARTUP
authors:
  - NotZachery
  - aakatz3
softdepend:
  - PlaceholderAPI
  - Vault
  - LuckPerms
  - StaffFacilities
api-version: 1.16
