name: ${project.name}
version: ${project.version}
main: com.dumbdogdiner.StickyCommands.Main
load: STARTUP
authors: [NotZachery]
softdepend: [Vault]
api-version: 1.14
commands:
  top:
    description: Teleport to the highest block above you
  jump:
    description: Jump to the block you are looking at
  speed:
    description: Set your walk or fly speed
  seen:
    description: Check when a player was last online
  stickycommands:
    description: Reload the plugin
  smite:
    description: Smite a player
  worth:
    description: Get the worth of an item
  sell:
    description: Sell items in your hand, or inventory
  afk:
    description: Set yourself to AFK
  hat:
    description: Have a hat!
  item:
    description: Give yourself items!
    aliases: [i,give]
  memory:
    description: check server memory!
    aliases: [lag,elag,egc,mem,emem,memory,ememory,uptime,euptime,tps,etps,entities,eentities]